#ifndef _CONFIG_H_
#define _CONFIG_H_

#define GL_GLEXT_PROTOTYPES

#define WIDTH_SCREEN 640
#define HEIGHT_SCREEN 640

#define BORDE_IZQUIERDO 1<<0
#define BORDE_SUPERIOR  1<<1
#define BORDE_DERECHO   1<<2
#define BORDE_INFERIOR  1<<3

#define FPS_LIMIT 30.0f
#define FPS_DELAY 1000.0f / FPS_LIMIT

/***SPRITES***/

#define MODULES_BALAS_BALA			0
#define MODULES_BALAS_MAX			MODULES_BALAS_BALA+1

#define MODULES_TEXTO_TITULO		0
#define MODULES_TEXTO_NOMBRE		MODULES_TEXTO_TITULO+1
#define MODULES_TEXTO_MENU_OPCION1	MODULES_TEXTO_NOMBRE+1
#define MODULES_TEXTO_MENU_OPCION2	MODULES_TEXTO_MENU_OPCION1+1
#define MODULES_TEXTO_MENU_OP1_SEL	MODULES_TEXTO_MENU_OPCION2+1
#define MODULES_TEXTO_MENU_OP2_SEL	MODULES_TEXTO_MENU_OP1_SEL+1
#define MODULES_TITULOS_MAX			MODULES_TEXTO_MENU_OP2_SEL+1

#define MODULES_ENEMIGO_NAVE		0
#define MODULES_ENEMIGO_MAX			MODULES_ENEMIGO_NAVE+1

#define MODULES_GANASTE_FONDO		0
#define MODULES_GANASTE_MAX			MODULES_GANASTE_FONDO+1

#define MODULES_JUGANDO_FONDO		0
#define MODULES_JUGANDO_MAX			MODULES_JUGANDO_FONDO+1

#define MODULES_MENU_FONDO			0
#define MODULES_MENU_MAX			MODULES_MENU_FONDO+1

#define MODULES_PERDISTE_FONDO		0
#define MODULES_PERDISTE_MAX		MODULES_PERDISTE_FONDO+1

#define MODULES_MINAVE_NAVE			0
#define MODULES_MINAVE_MAX			MODULES_MINAVE_NAVE+1

/////////////////////


#define MAXIMO_DE_BALAS 30
#define MAXIMO_DE_NIVELES 5
#define MAXIMO_DE_ENEMIGOS 15

#define NAVE_PROPIA 0
#define NAVE_ENEMIGA 1

#define CERO 0
#define UNO 1


#endif